---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
library(glue)
```
# TCGApipelines

## Data

```{r echo=FALSE}
x <- tibble::tribble(
   ~ `Short Name`, ~ Source, ~ docs, ~Data, ~ Link
   , "tcga-liu2018", "Liu et. al., Cell (2018)", TRUE, "data/tcga-liu2018_clinData.csv", "https://doi.org/10.1016/j.cell.2018.02.052"
   , "tcga-cgds_prad", "cBioPortal (TCGA, Provisional)", FALSE, "data/tcga-cgds_prad.csv", "http://www.cbioportal.org/study?id=prad_tcga#summary"
   , "tcga-cgds_prad-cell", "cBioPortal (TCGA, Cell)", FALSE, "data/tcga-cgds_prad-cell.csv", "http://www.cbioportal.org/study?id=prad_tcga_pub#summary"
)

x %>% 
   mutate(
      docs = ifelse(docs, glue("[docs/{`Short Name`}](docs/{`Short Name`})"), ""),
      Data = ifelse(Data != "", glue("[{sub('data/', '', Data)}]({Data})"), ""),
      Link = ifelse(Link != "", glue("[Link]({Link})"), ""),
      `Short Name` = glue("`{`Short Name`}`")
   ) %>% 
   rename(`Related Docs` = docs) %>% 
   knitr::kable()
```
