#' ---
#' output: github_document
#' ---

#+ include=FALSE
knitr::opts_chunk$set(echo = TRUE)
# tcga_cell <- readRDS(here::here("data/tcga-cgds_prad-cell.rds"))

#+ library, message=FALSE, warning=FALSE
library(tidyverse)
library(different)

#' ## Load Data
tcga_liu2018 <- readRDS(here::here("data/tcga-liu2018_clinData.rds"))
tcga_cgds <- readRDS(here::here("data/tcga-cgds_prad.rds"))

#' Liu 2018 contains multiple cancer types.
#' We need to filter down to `"PRAD"`.
tcga_liu2018 <- filter(tcga_liu2018, type == "PRAD")

#' Quick look at dimensions
dim(tcga_liu2018)
dim(tcga_cgds)

#' ## Match ID Column
#' 
#' Columns containing IDs have different column names and format.
tcga_liu2018 %>% slice(1:5) %>% select(bcr_patient_barcode)
tcga_cgds %>% slice(1:5) %>% select(id)

#' In general, it seems that Liu 2018 drops the trailing `.NN` and replaces
#' `.` with `-` characters. Here's a quick function that transforms the IDs.
cgds_to_liu2018_id <- function(ids) {
   ids <- str_remove(ids, "\\.\\d{2}$")
   str_replace_all(ids, "\\.", "-")
}

#' Verify this function gives thes same format for both IDs.
tcga_liu2018$bcr_patient_barcode[1]
cgds_to_liu2018_id(tcga_cgds$id[1])

#' The IDs in the CGDS dataset contain a trailing `.NN`. Are these always `.01`?
tcga_cgds %>% 
   select(id) %>% 
   mutate(`Trailing Digits` = str_extract(id, "\\d{2}$")) %>% 
   group_by(`Trailing Digits`) %>% 
   count() %>% 
   knitr::kable()

#' Which ID ends with `.06`?
cgds_odd_id <- tcga_cgds %>% 
   filter(str_detect(id, "06$")) %>% 
   pull(id)

cgds_odd_id

#' Is this ID otherwise unique?
cgds_odd_data <- tcga_cgds %>% 
   filter(str_detect(id, str_remove(cgds_odd_id, "\\.\\d{2}$"))) %>% 
   select(1:10)

knitr::kable(cgds_odd_data)

#' Are there differences in this data?
different::tidy_diff(cgds_odd_data[1, ], cgds_odd_data[2, ])

#' The only difference in the CGDS data between these two IDs is the ID itself.
#' Does this ID appear in the Liu2018 data?
tcga_liu2018 %>% 
   filter(bcr_patient_barcode %in% cgds_to_liu2018_id(cgds_odd_id)) %>% 
   select(1:5) %>%
   knitr::kable()

#' Okay, so we'll drop the duplicated patient from CGDS with the `.06` ID.
tcga_cgds <- tcga_cgds %>%
   filter(id != cgds_odd_id)

#' Process CGDS dataset to match Liu2018
tcga_cgds <- tcga_cgds %>%
   mutate(id = cgds_to_liu2018_id(id)) %>% 
   rename(bcr_patient_barcode = id)

#' Liu2018 contains two additional participants not included in the CGDS dataset
tcga_liu2018 %>% 
   filter(!bcr_patient_barcode %in% tcga_cgds$bcr_patient_barcode) %>% 
   select(bcr_patient_barcode, type, last_contact_days_to) %>% 
   knitr::kable()

#' So we'll remove those patients for further comparison
tcga_liu2018 <- tcga_liu2018 %>%
   filter(bcr_patient_barcode %in% tcga_cgds$bcr_patient_barcode)

#' ## First look at differences
#' 
#' Arrange both datasets by ID so that to align the rows.
tcga_cgds <- arrange(tcga_cgds, bcr_patient_barcode)
tcga_liu2018 <- arrange(tcga_liu2018, bcr_patient_barcode)

#' Let `different` take a shot at the data
tcga_diff <- tidy_diff(tcga_cgds, tcga_liu2018)

summary(tcga_diff)

#' ## Matching Columns
#' 
#' Column matching rules were generated by comparing columns by hand,
#' visually inspecting values, etc.
source(here::here("docs/compare-cgds-vs-liu2018/match_rules.R"))
knitr::kable(match_rules)

tcga_liu2018_matched <- tcga_liu2018[, match_rules$liu2018]
colnames(tcga_liu2018_matched) <- match_rules$merged

tcga_cgds_matched <- tcga_cgds[, match_rules$cgds]
colnames(tcga_cgds_matched) <- match_rules$merged

tcga_diff <- tidy_diff(tcga_cgds_matched, tcga_liu2018_matched)
summary(tcga_diff)

plot(tcga_diff)


#' ## Transformations
#' 
#' As seen in the previous plot, there are 8 columns that are completely different.
#' This is most likely the result of recoding categorical variables (e.g. `1` vs `Deceased`)
#' or of a difference in units (e.g. *months* vs *days*).

#+ fig.height=10, fig.width=16, echo=FALSE
vars_totally_different <- filter(tcga_diff$diff, miss_count >= 400)$variable

tcga_diff$tidy[vars_totally_different] %>%
  imap(~ ggplot(.x) + 
          aes(x = value.x, y = value.y) + 
          geom_point() + 
          labs(x = tcga_diff$meta$names["x"], 
               y = tcga_diff$meta$names["y"], 
               title = .y)
  ) %>%
  cowplot::plot_grid(plotlist = ., ncol = 4)


#' Of the variables that are completely different one results from a scaling difference.
OS.time_lm <- tcga_diff$tidy$OS.time %>% lm(value.y ~ value.x, data = .)
OS.time_lm

#' Looks like this is a result of converting overall survival time from months (decimal)
#' to days (integer).
#' ![The first search result for "how to convert months to days".](convert-months-to-days.png)
ggplot(tcga_diff$tidy$OS.time) +
   aes(x = value.x, y = value.y - round(value.x * 30.4375), 0) +
   geom_point() + 
   labs(x = "CGDS Overall Survival Time [months]", 
        y = "Liu [days \U2192 months] - CGDS [months]",
        title = "round(Liu [days] / 30.4375, 0)")

#' Rounding like this is destructive, so we can only modify the value expressed
#' in months to be able to compare the values directly.
tcga_cgds_matched <- tcga_cgds_matched %>%
  mutate(OS.time = round(OS.time * 30.4375, 0))

#' Now we can convert the categorical differences.
#' Here are three examples of the recoding that takes place.
#+ echo=FALSE
diff_colnames <- c("Value in Liu2018", "Value in CGDS", "n")

#+ echo=TRUE
tcga_diff$tidy %>% 
   .[vars_totally_different[-length(vars_totally_different)]] %>% 
   map(~ group_by(., value.y, value.x) %>% 
              count() %>%
              mutate_if(is.double, function(x) paste(round(x, 4))) %>% 
              mutate_all(as.character),
           .id = "variable") %>% 
   .[1:3] %>% 
   knitr::kable(col.names = diff_colnames)

#' The following encodes the rules to move from the CGDS dataset
#' to the Liu2018 dataset.
tcga_cgds_matched <- tcga_cgds_matched %>%
   mutate(
      type = "PRAD",
      gender = toupper(gender),
      OS = as.integer(OS == "DECEASED"),
      race = case_when(
         race == "" ~ "[Not Available]",
         TRUE ~ race
      )
   )

tcga_liu2018_matched <- tcga_liu2018_matched %>%
  mutate(
     clinical_stage = NA,
     cause_of_death = case_when(
        vital_status == "Alive" ~ "",
        TRUE ~ cause_of_death
     )
  )

#' ## Final Diff
tcga_diff <- tidy_diff(tcga_cgds_matched, tcga_liu2018_matched)
summary(tcga_diff)

#' ## Final Differences Report
#' 
#' ### Omissions
#' 
#' The `clinical_stage` and `residual_tumor` columns were included in the Liu2018 dataset, but the values were replaced with `[Not Applicable]`.
#' 
#' ### Transformations
#' 
#' The following columns needed to be transformed:
#' 
#' - `os_months` was converted to `OS.time` by multiplying by 30.4375 and rounding to the nearest integer.
#' - `cancer_type` was renamed `type` and replaced with the short form `PRAD`
#' - `sex` was renamed `gender` and made uppercase
#' - `os_status` was renamed `OS` and coded as an integer where `1 == "DECEASED"`
#' - `race` was coded as `"[Not Available]"` if not supplied in the CGDS dataset
#' - `patient_death_reason` was renamed `cause_of_death` and was coded as `"[Not Availble]"` when blank in the original dataset (including for patients who were still alive)
#' 
#' ### Updates
#'  
#' The following variables were updated in the Liu2018 dataset.
#' 
#' #### `last_contact_days_to`
#' 
#' It's really not clear to me how this was updated.
left_join(tcga_liu2018_matched, tcga_cgds_matched, by = "bcr_patient_barcode",
          suffix = c(".liu", ".cgds")) %>% 
   # select(bcr_patient_barcode, starts_with("last_contact_days_to")) %>% 
   mutate(diff = last_contact_days_to.liu - last_contact_days_to.cgds) %>% 
   ggplot() +
   aes(x = bcr_patient_barcode, color = vital_status.liu, y = diff) +
   geom_point() +
   theme(axis.text.x = element_blank())

#' #### `treatment_outcome_first_course`
#' 
#' Liu2018 appears to have updated a large number of the values that were previously blank in CGDS.

tcga_diff$tidy %>% 
   .["treatment_outcome_first_course"] %>% 
   map(~ group_by(., value.y, value.x) %>% 
          count() %>%
          mutate_if(is.double, function(x) paste(round(x, 4))) %>% 
          mutate_all(as.character),
       .id = "variable") %>% 
   knitr::kable(col.names = diff_colnames)

#' #### `tumor_status`
#' 
#' Similarly, tumor status was updated as well.
#' 
tcga_diff$tidy %>%
   .["tumor_status"] %>% 
   map(~ group_by(., value.y, value.x) %>% 
          count() %>%
          mutate_if(is.double, function(x) paste(round(x, 4))) %>% 
          mutate_all(as.character),
       .id = "variable") %>% 
   knitr::kable(col.names = diff_colnames)

#' #### `cause_of_death`
#' 
tcga_diff$tidy %>% 
   .["cause_of_death"] %>% 
   map(~ group_by(., value.y, value.x) %>% 
          count() %>%
          mutate_if(is.double, function(x) paste(round(x, 4))) %>% 
          mutate_all(as.character),
       .id = "variable") %>% 
   knitr::kable(col.names = diff_colnames)

#' #### `death_days_to`
tcga_diff$tidy %>% 
   .["death_days_to"] %>% 
   map(~ group_by(., value.y, value.x) %>% 
          count() %>%
          mutate_if(is.double, function(x) paste(round(x, 4))) %>% 
          mutate_all(as.character),
       .id = "variable") %>% 
   knitr::kable(col.names = diff_colnames)

#' #### `new_tumor_event_dx_days_to`
#'
#' Values missing in CGDS are at y-axis, values missing in Liu2018 are on X axis.
tcga_diff$tidy$new_tumor_event_dx_days_to %>%
  mutate_at(vars(starts_with("value")), function(x) ifelse(is.na(x), 0, x)) %>%
  ggplot(aes(x = value.x, y = value.y)) + geom_point()