---
output: github_document
---

## Clinical data exploration example: prostate

`r Sys.Date()`

*** 

Data used here was downloaded from TCGA's pan-cancer clinical data resource from Supplementary Table 1 of [this paper](https://www.cell.com/cell/fulltext/S0092-8674(18)30229-0).

```{r message=FALSE}
library(here)
library(tidyverse)

load(here("data", "tcga-liu2018_clinData.RData"))

# filter to PRAD
dat <- dat %>% filter(type=="PRAD")
glimpse(dat)
```

Try to figure out how time to event variables are created.

```{r}
# OS.time and DSS.time are the same thing
all.equal(dat$OS.time, dat$DSS.time)

# new_tumor_event_type seems to denote what sort of event was recorded
table(dat$new_tumor_event_type, useNA="ifany")

# 5 patients with unequal DFI and PFI times when DFI is not mising, all have new primaries
dat %>% 
   filter(DFI.time != PFI.time) %>% 
   select(bcr_patient_barcode, new_tumor_event_type, DFI.time, PFI.time) %>% 
   knitr::kable() 

# what about those with BCR?
dat %>% 
   filter(new_tumor_event_type=="Biochemical evidence of disease") %>% 
   select(bcr_patient_barcode, new_tumor_event_type, DFI.time, PFI.time) %>% 
   knitr::kable() 

# look at time to BCR in days and then in months
BCRdat <- dat %>% filter(new_tumor_event_type=="Biochemical evidence of disease")
summary(BCRdat$PFI.time)
summary(BCRdat$PFI.time/30.5)
```

